'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Fundamental_Utilities.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Animation_BlackLoader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Animation_BlackLoader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Animation_GreenLoader() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Animation_GreenLoader", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property arrow_Right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("arrow_Right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property badge_bgleft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("badge_bgleft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property badge_Entertainment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("badge_Entertainment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property badge_Filesystem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("badge_Filesystem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property badge_Filesystem1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("badge_Filesystem1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property badge_Internet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("badge_Internet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property badge_MainUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("badge_MainUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property badge_MyComputer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("badge_MyComputer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property badge_worldmap() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("badge_worldmap", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BCL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BCL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_BlackVista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_BlackVista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_Facebook() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_Facebook", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_Header() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_Header", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_MainSplash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_MainSplash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_Menubar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_Menubar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_Menubar2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_Menubar2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_Panelwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_Panelwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_Sidebar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_Sidebar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_SplashBYE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_SplashBYE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_SubSplashs() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_SubSplashs", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_TaskmgrHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_TaskmgrHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_TaskmgrNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_TaskmgrNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_Vista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_Vista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg_XPPowerstate() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_XPPowerstate", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BSN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BSN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_FileDownloaderHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_FileDownloaderHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_FileDownloaderNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_FileDownloaderNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_FileUploadHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_FileUploadHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_FileUploadNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_FileUploadNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_GIDHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_GIDHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_GIDNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_GIDNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_IViewerHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_IViewerHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_IViewerNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_IViewerNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_MPlayerHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_MPlayerHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_MPlayerNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_MPlayerNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_WebBrowserHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_WebBrowserHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property button_WebBrowserNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_WebBrowserNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonGreenH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonGreenH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonGrey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonGrey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ButtonGreyH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonGreyH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Calchelp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calchelp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1252\uc1\adeff31507\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang1033\deflangfe1033\themelang1033\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        '''{\f37\fbidi \fswiss\fcharset0\fprq2{\*\panose 020f0502020204030204}Calibri;}{\f38\fbidi \fswiss\fcharset0\fprq2{\*\panose 020b0604030504040204}Tahoma;}{\f39\fbi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property EULA() As String
            Get
                Return ResourceManager.GetString("EULA", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property ico_AB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_AB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_AddToList() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_AddToList", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Alarm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Alarm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_alpha_CPU_16x16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_alpha_CPU_16x16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_alpha_programmstart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_alpha_programmstart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Analyser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Analyser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Analyserpng() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Analyserpng", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Attributes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Attributes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_BatteryCharging() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_BatteryCharging", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_BatteryFull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_BatteryFull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_BatteryLow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_BatteryLow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_BatteryNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_BatteryNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Calculator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Calculator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Calender() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Calender", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Camera() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Camera", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Chart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Chart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Clock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Clock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Clockbig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Clockbig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_cpu3d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_cpu3d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_CPUBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_CPUBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Critical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Critical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Crown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Crown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_deletesmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_deletesmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_encrypt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_encrypt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ico_EnergyOptions() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_EnergyOptions", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Exclamation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Exclamation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Exiting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Exiting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Favorites() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Favorites", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Folderimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Folderimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Fonts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Fonts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_GO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_GO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_GoArrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_GoArrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Google() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Google", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_GreenPlus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_GreenPlus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_NFS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_NFS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Notepad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Notepad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Pictures() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Pictures", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Plug() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Plug", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Plugin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Plugin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_powerpreferences() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_powerpreferences", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_ProgramDeactivator() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_ProgramDeactivator", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Progress() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Progress", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Projection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Projection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Protection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Protection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ico_RAMBig() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ico_RAMBig", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_RefreshSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_RefreshSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Registry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Registry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Rename() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Rename", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_RepairWizard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_RepairWizard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_reportcenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_reportcenter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Reset() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Reset", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_risky() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_risky", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_SandClock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_SandClock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_scan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_scan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_SecurityCenteSmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_SecurityCenteSmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Service() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Service", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_ServiceManager() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_ServiceManager", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_ServicePause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_ServicePause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_ServiceResume() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_ServiceResume", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_ServiceStart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_ServiceStart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_ServiceStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_ServiceStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_SessionLogout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_SessionLogout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Shredder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Shredder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_sidebar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_sidebar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_SingnalFull() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_SingnalFull", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_SingnalNone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_SingnalNone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Spanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Spanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_SwapFile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_SwapFile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Switchoff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Switchoff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_SwitchOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_SwitchOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_System() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_System", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Systemunit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Systemunit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Taskbar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Taskbar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Tools() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Tools", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Undo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Undo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_Update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_Update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_UserInfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_UserInfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ico_web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ico_web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_RescueCenter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_RescueCenter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Intergrater3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Intergrater3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property layerbutton_Hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("layerbutton_Hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property layerbutton_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("layerbutton_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LED_Green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED_Green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LED_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LED_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_Aloysius() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_Aloysius", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_Compatible() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_Compatible", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_Fundamental() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_Fundamental", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_GoogleImages() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_GoogleImages", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_registry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_registry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_SriLanka() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_SriLanka", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo_Windows() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo_Windows", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property loop_KKid() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("loop_KKid", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property minimize_hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimize_normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimize_normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pic_About() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic_About", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pic_About1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pic_About1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property royal_browser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("royal_browser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sfx_Ding() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sfx_Ding", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sfx_FeedDiscovered() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sfx_FeedDiscovered", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sfx_Logoff() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sfx_Logoff", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sfx_Logon() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sfx_Logon", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sfx_Navigation() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sfx_Navigation", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sfx_Photoflash() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sfx_Photoflash", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property sfx_PopupBlocked() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("sfx_PopupBlocked", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Shredder() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Shredder", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Side_Systemdevices() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Side_Systemdevices", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SideBarMU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SideBarMU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallswitch_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallswitch_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallswitch_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallswitch_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tab_Active() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tab_Active", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tab_Hover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tab_Hover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tab_Normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tab_Normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
